# Generated by Django 3.0.5 on 2020-04-15 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diarioDtAtual', models.DateField(verbose_name='Data atual ')),
                ('diarioNumDiario', models.IntegerField(verbose_name='Número do diário')),
                ('diarioDiasTrab', models.IntegerField(verbose_name='Dias trabalhados')),
                ('diarioSaldoPraz', models.IntegerField(verbose_name='Saldo de dias restantes')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empClienteRazao', models.CharField(max_length=50, verbose_name='Nome da razão social')),
                ('empClienteCNPJ', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('empClienteRespon', models.CharField(max_length=50, verbose_name='Responsável')),
                ('empClienteContato', models.CharField(max_length=12, verbose_name='Contato')),
                ('empClienteEmail', models.EmailField(max_length=254, verbose_name='Email')),
                ('endRua', models.CharField(max_length=50, verbose_name='Rua')),
                ('endNum', models.IntegerField(verbose_name='Número')),
                ('endCEP', models.CharField(max_length=50, verbose_name='CEP')),
                ('endCidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('endEstado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('empreUserRazao', models.CharField(max_length=50, verbose_name='Nome da razão social')),
                ('empreUserCNPJ', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('empreUserRespon', models.CharField(max_length=50, verbose_name='Responsável')),
                ('empreUserContato', models.CharField(max_length=12, verbose_name='Contato')),
                ('empreUserEmail', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('endRua', models.CharField(max_length=50, verbose_name='Rua')),
                ('endNum', models.IntegerField(verbose_name='Número')),
                ('endCEP', models.CharField(max_length=50, verbose_name='CEP')),
                ('endCidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('endEstado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QtdServ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QtdServMaoObra', models.IntegerField(verbose_name='Quantidade geral de Mão de Obras')),
                ('QtdServEquip', models.IntegerField(verbose_name='Quantidade geral de Equipamentos')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diario.Diario')),
            ],
        ),
        migrations.CreateModel(
            name='Observacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsDescServ', models.TextField(verbose_name='Descrição dos Serviços')),
                ('obsComentario', models.TextField(verbose_name='Comentário')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diario.Diario')),
            ],
        ),
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obraNome', models.CharField(max_length=30, verbose_name='Nome ')),
                ('obraPrazContrat', models.DateField(verbose_name='Prazo do Contrato(data)')),
                ('empresaCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diario.EmpresaCliente')),
                ('empresaUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaoObrasIndiretas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maoObraIndDesc', models.CharField(max_length=50, verbose_name='Descrião')),
                ('maoObraIndQtd', models.IntegerField(verbose_name='Quantidade')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diario.Diario')),
            ],
        ),
        migrations.CreateModel(
            name='MaoObrasDiretas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maoObraDirDesc', models.CharField(max_length=50, verbose_name='Descrição')),
                ('maoObraDirQtd', models.IntegerField(verbose_name='Quantidade')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diario.Diario')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipDesc', models.CharField(max_length=50, verbose_name='Descrição')),
                ('EquipQtd', models.IntegerField(verbose_name='Quantidade')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diario.Diario')),
            ],
        ),
        migrations.AddField(
            model_name='empresacliente',
            name='engenheiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmpreiteirasMaoObras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empMaoObraDesc', models.CharField(max_length=50, verbose_name='Descrição')),
                ('empMaoObraQtd', models.IntegerField(verbose_name='Quantidade')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diario.Diario')),
            ],
        ),
        migrations.CreateModel(
            name='EmpreiteirasEquipamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empEquipDesc', models.CharField(max_length=50, verbose_name='Descrição')),
                ('empEquipQtd', models.IntegerField(verbose_name='Quantidade')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diario.Diario')),
            ],
        ),
        migrations.AddField(
            model_name='diario',
            name='chave_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diario.Obras'),
        ),
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climaManha', models.CharField(max_length=20, verbose_name='Condições do tempo manhã')),
                ('climaTarde', models.CharField(max_length=20, verbose_name='Condições do tempo tarde')),
                ('climaNoite', models.CharField(max_length=20, verbose_name='Condições do tempo noite')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diario.Diario')),
            ],
        ),
    ]
